### ISSUE TITLE
Readme instructs to config using Join mechanism instead the Discovery SPI

### ISSUE THREAD

**Issue by idogal** [hazelcast/hazelcast-aws#119]
Hi,

Commit 925285cfdf621ddb8f65c1857d7b9a24bb9f16d8
reverted the readme back to instruct using the Join mechanism as before commit  2cfc2520089701c4eb7796e306e6728874cdc1e0.

I wonder what is the reason for that, and what is currently the best practice for that.

I upgraded the AWS plugin from 1.1 to 2.4 and have had problems with the Join mechanism, that seem to be solved when configuring with the AwsDiscoveryStrategy.

Thanks

**Comment by leszko** [comment]
Thanks for asking the question @idogal This is actually a very good question.

So, the long story short:
- First, there was `<aws>` mechanism
- It became deprecated, because we developed `<discovery-strategy>` which were better
- The old `<aws>` mechanism was finally removed and the `<discovery-strategy>` is not aliased with `<aws>`.

So now, technically using `<aws>` is exactly the same as using `<discovery-strategy>`, but we recommend using `<aws>`, because the configuration looks more clear. We keep README up-to-date, so you can treat it as a single point of truth.

**Comment by idogal** [comment]
@leszko Thanks!

Since which version did you drop the old `aws` mechanism? Thanks

**Comment by leszko** [comment]
Since `2.4` (and Hazelcast `3.12`). But check also the compatibility notes at the beginning of the README. The version of `hazelcast-aws` needs to be compatible with the `hazelcast` version.
