### ISSUE TITLE
ECS Clients tries to fetch public IPs despite AwsConfig#usePublicIp=false

### ISSUE THREAD

**Issue by invadersmustdie** [hazelcast/hazelcast-aws#210]
Steps to reproduce:
- setup ECS tasks
- do not grant permission for `ec2:DescribeNetworkInterfaces` 
- set `AwsConfig#usePublicIp` to `false`

Actual behavior:
- `AwsEcsClient#getAddresses()` tries to resolve public IPs via `awsEc2Api.describeNetworkInterfaces`
- results in retries `Couldn't connect to the AWS service, [3] retrying in 3 seconds` and error `Cannot fetch public IPs of ECS Tasks, only private addresses are used. If you need to access Hazelcast with public IP, please check if your Task has IAM role which allows querying EC2 API` 

Expected behavior:
- `AwsEcsClient#getAddresses()` does not try to resolve public IPs if `AwsConfig#usePublicIp` is set to `false`

**Comment by leszko** [comment]
Which Hazelcast version do you use?

**Comment by DirkRusche** [comment]
We are using

- com.hazelcast:hazelcast:4.0.2
- com.hazelcast:hazelcast-aws:3.3
- com.hazelcast:hazelcast-spring:4.0.2

**Comment by enozcan** [comment]
If use-public-ip is not explicitly set to true, the discovery mechanism still attempts to fetch public IPs if available. The reason is to make external Hazelcast smart clients (if there is any) work as expected (i.e. ask to the partition owner member of a key directly in favor of performance. See the details for smart client [here in Java client section](https://docs.hazelcast.org/docs/latest/manual/html-single/#getting-started-with-java-client) which also works the same way with other clients). After the discussions in #218, with #220 the log message is changed to indicate that the configuration is still valid when use-public-ip is false but not appropriate to use with external smart clients. Since it's not concluded as a bug, closing the issue. Please ask/reopen if you have further questions.
