### ISSUE TITLE
Why don't you use the AWS SDK?

### ISSUE THREAD

**Issue by hoegertn** [hazelcast/hazelcast-aws#4]
Is there a special reason why you do not use the SDK?

I think credentials management and API calls would be a lot easier. This would lead to more advanced discovery mechanisms based on AWS.

**Comment by mesutcelik** [comment]
Hi @hoegertn ,

Thanks for the question.

It is mainly because Hazelcast does always prefer having no external dependency in their modules. 
Additionally, this module is mostly in maintenance mode nowadays so we don't see any reason for such refactoring.

For Hazelcast related questions, [Hazelcast Google Groups](https://groups.google.com/forum/#!forum/hazelcast) is the best place to watch.

I am closing this issue so please feel free to [create issues](https://github.com/hazelcast/hazelcast/issues/new) for bugs/feature requests.

**Comment by hoegertn** [comment]
What do you mean by "maintenance mode"? What is the new way to cluster on AWS?

**Comment by mesutcelik** [comment]
`maintenance mode` means that we don't add features regularly to this module.

You can check [this documentation](http://docs.hazelcast.org/docs/latest/manual/html-single/#discovering-members-within-ec2-cloud) how to form cluster on AWS with hazelcast 3.6.x

`hazelcast-aws` is a new repository for the old `hazelcast-cloud` module. The only change is the name of the module in the new repository.  `hazelcast-aws` hasn't been released yet as we haven't added any new feature. Therefore, you should have a look [Hazelcast repository](https://github.com/hazelcast/hazelcast/tree/maintenance-3.x/hazelcast-cloud) for the latest stable version.

Can you describe your requirement? Are you talking about a missing feature or do you see a bug while forming cluster on AWS?

**Comment by kobalski** [comment]
@hoegertn You can also implement your custom discovery strategy according to your needs with the help of discovery spi. Please  check out the docs : http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#discovery-spi. You can find reference implementations such as jclouds and azure under hazelcast repo. 
https://github.com/hazelcast/hazelcast-jclouds
https://github.com/hazelcast/hazelcast-azure

**Comment by hoegertn** [comment]
The idea is to discover cluster instances by adding all members of the autoscaling group the instance is a member of. I will implement it as a discovery strategy. Thanks for the hint.
