### ISSUE TITLE
Proxy support for hazelcast (AWS)?

### ISSUE THREAD

**Issue by planet** [hazelcast/hazelcast-aws#44]
In our AWS environment the EC2 endpoint is only reachable via a proxy server, as there is no other way to get to the Internet.  Does hazelcast support this?  If so how can we configure hazelcast to discovery members via a proxy?  Thanks in advance!

**Comment by googlielmo** [comment]
The AWS discovery plugin uses `java.net.HttpURLConnection`, which supports this use case.

Please set the `http.proxyHost` and `http.proxyPort` system properties, or their https counterparts `https.proxyHost` and `https.proxyPort`, to specify your http, or https, proxy host and port  [1].

Also, set the `http.nonProxyHosts` (which is also used for https!) to the value "169.254.169.254|169.254.170.2", so that the `hazelcast-aws` plugin can access the Instance Meta Data Service [2] and the IAM Roles for Tasks Service [3].

Hope this helps.

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
[2] http://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html
[3] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Comment by planet** [comment]
Thanks @googlielmo
